name : "Hello World Workflow"

# controls the actions when it will run. it will trigger the workflow on push done either in the master or in the production branch 
on: 
  push:
    branches:
      - master
      - main
      - production

jobs:
  hello_world:
    # environment of the runner machine where the workflow will run, and it's a github hoted environment so we can choose any platform like the ubantu-latest or the windows-latest etc.
    runs-on: ubuntu-latest
    steps:
      - name: "Hello world"
        run: echo "Hello world" 
      
      - name: "Print the current date and time"
        run: date