name : "Multi event pipeline/workflows" # name of the workflow
on: # define on which events the workflow will run
    push: # event name
        branches:
            - master
            - test
    pull_request: # event name
        branches:
            - master
    workflow_dispatch: # event name to trigger the workflow from the github ui


jobs:
    on-push: # job name
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps: # steps are the commands that will be executed
            - name: "Running on master/test push" # name of the step
              run: echo "Running on master/test push" # command to be executed3

    on-pull-request: # job name
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps: # steps are the commands that will be executed
            - name: "Running on master pull request" # name of the step
              run: echo "Running on master pull request" # command to be executed

    on-workflow-dispatch: # job name
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on workflow dispatch" # name of the step
              run: echo "Running on workflow dispatch" # command to be executed
