name : "Multi event pipeline/workflows" # name of the workflow
on: # define on which events the workflow will run
    push: # event name
        branches:
            - master
            - test
    schedule: # event name
        - cron: '0 10 * * 2,4' # run the workflow every day at 10:00 AM on Tuesday and Thursday
    pull_request: # event name
        branches:
            - master
            - main
        types:
            - closed
            - opened
    workflow_dispatch: # event name to trigger the workflow from the github ui


jobs:
    on-push: # job name
        if: github.event_name == 'push' 
        runs-on: ubuntu-latest
        steps: # steps are the commands that will be executed
            - name: "Running on master/test push" # name of the step
              run: echo "Running on master/test push" # command to be executed3

    on-pull-request: # job name
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps: # steps are the commands that will be executed
            - name: "Running on master/main pull request" # name of the step
              run: echo "Running on master/main pull request" # command to be executed

    on-pull-request-opened: # job name
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request opened" # name of the step
              run: echo "Running on pull request opened" # command to be executed

    on-pull-request-closed: # job name
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request closed" # name of the step
              run: echo "Running on pull request closed" # command to be executed

    on-workflow-dispatch: # job name
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on workflow dispatch" # name of the step
              run: echo "Running on workflow dispatch" # command to be executed

    on-schedule: # job name
        if: github.event_name == 'schedule'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on schedule" # name of the step
              run: echo "Running on schedule" # command to be executed
